In [1]:
import import_ipynb
import glob

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
import matplotlib.pyplot as plt


In [2]:
df= pd.read_csv('kidney_disease.csv')
print(df.head())

   id   age    bp     sg   al   su     rbc        pc         pcc          ba  \
0   0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent  notpresent   
1   1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent  notpresent   
2   2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3   3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4   4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   

   ...  pcv    wc   rc  htn   dm  cad appet   pe  ane classification  
0  ...   44  7800  5.2  yes  yes   no  good   no   no            ckd  
1  ...   38  6000  NaN   no   no   no  good   no   no            ckd  
2  ...   31  7500  NaN   no  yes   no  poor   no  yes            ckd  
3  ...   32  6700  3.9  yes   no   no  poor  yes  yes            ckd  
4  ...   35  7300  4.6   no   no   no  good   no   no            ckd  

[5 rows x 26 columns]


In [3]:
df.shape

(400, 26)

In [4]:
columns_to_retain=['sg','al','sc','hemo','pcv','wbcc','rbcc','htn','classification']
df = df.drop([col for col in df.columns if not col in columns_to_retain], axis=1)
df = df.dropna(axis=0)

In [5]:
for column in df.columns:
    if df[column].dtype == np.number:
        continue
    df[column] = LabelEncoder().fit_transform(df[column])

    

<ipython-input-5-f2b76d385570>:2: DeprecationWarning: Converting `np.inexact` or `np.floating` to a dtype is deprecated. The current result is `float64` which is not strictly correct.
  if df[column].dtype == np.number:


In [6]:
df.head()

sg   al   sc  hemo  pcv  htn  classification
0  1.020  1.0  1.2  15.4   28    1               0
1  1.020  4.0  0.8  11.3   22    0               0
2  1.010  2.0  1.8   9.6   15    0               0
3  1.005  4.0  3.8  11.2   16    1               0
4  1.010  2.0  1.4  11.6   19    0               0

In [7]:
X = df.drop(['classification'],axis=1)
y = df['classification']

In [8]:
x_scaler = MinMaxScaler()
x_scaler.fit(X)
column_names = X.columns
X[column_names] = x_scaler.transform(X)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, shuffle=True)

In [10]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

In [11]:
from sklearn.ensemble import RandomForestClassifier

In [12]:
clf = RandomForestClassifier(n_estimators = 100)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

In [17]:
from sklearn import metrics
print("accuracy", metrics.accuracy_score(y_test, y_pred))

accuracy is 9.8


In [18]:
clf.predict([[1.01,3,1.6,11.4,20,0]])

array([0])

In [19]:
pipe=Pipeline([
    ('rescale',StandardScaler()),
    ('classifier',RandomForestClassifier())
])

In [20]:
X_train

sg   al        sc      hemo       pcv  htn
327  1.00  0.0  0.016949  0.700680  0.717949  0.0
176  0.25  0.8  0.055085  0.353741  0.179487  0.0
53   0.50  0.0  0.025424  0.714286  0.615385  1.0
237  0.50  0.4  0.076271  0.653061  0.615385  1.0
52   0.50  0.0  0.076271  0.530612  0.461538  0.0
..    ...  ...       ...       ...       ...  ...
147  0.25  0.6  0.055085  0.326531  0.230769  1.0
189  0.25  0.8  0.165254  0.435374  0.333333  1.0
279  1.00  0.0  0.008475  0.897959  0.820513  0.0
169  0.25  0.0  0.101695  0.380952  0.282051  1.0
11   0.25  0.6  0.097458  0.523810  0.410256  1.0

[229 rows x 6 columns]

In [21]:
pipe.fit(X_train,y_train)

Pipeline(steps=[('rescale', StandardScaler()),
                ('classifier', RandomForestClassifier())])

In [22]:
y_pred = pipe.predict(X_test)

In [25]:
pipe.predict([[1.01,0,0.6,11.4,20,0]])

array([1])

In [26]:
clf.predict([[1.01,0,0.6,11.4,20,0]])

array([1])